### ISSUE TITLE
لم يتم انتاج ملف `جيسون` كما هو متوقع

### ISSUE THREAD

**Issue by assawalhy** [alifcommunity/compiler#36]
<div dir=rtl>

واجهتنا مشكلة في التعديلات التي قام بها @me00001 في طلب السحب #35، المشكلة أني أحاول قراءة ملف السجل log على أنه json لكن يحدث خطأ، وطبعا هذا بسبب أ الملف ليس json.

الخطأ الذي يحدث عند قراءة ملف السِجلّ

<div dir=ltr>

```
         Traceback (most recent call last):
          File "./اختبارات/اختبر", line 335, in test_unit
            return do_test()
          File "./اختبارات/اختبر", line 266, in do_test
            logs = json.loads(f.read())
          File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
            return _default_decoder.decode(s)
          File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
            obj, end = self.raw_decode(s, idx=_w(s, 0).end())
          File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
            raise JSONDecodeError("Expecting value", s, err.value) from None
        json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

</div>

محتوى ملف السجل `أكواد/الإدخال/ادخل_رقما_سجل` هو طريقة عرض الخطأ القديمة:

<div dir=ltr>

```
        Please report this error to the Alif Community: https://github.com/alifcommunity/compiler/issues 
        
        Alif Compiler 3.0.32 (Beta) - Linux
        
        File : /home/runner/work/compiler/compiler/اختبارات/أكواد/الإدخال/ادخل_رقما.alif
        Error: 58:10: fatal error: boost/algorithm/string.hpp: No such file or directory   58 | #include <boost/algorithm/string.hpp>      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~compilation terminated.
        Compile command: g++ -c -o "/tmp/alifcompiler_1004.o" "/tmp/alifcompiler_1004.cpp" -I"/usr/local/lib/aliflib"   -Wall -std=gnu++17 -m64 -finput-charset=utf-8 -O3 -pthread -DNDEBUG -fvisibility=hidden   2> "/tmp/alifcompiler_1004_compile.log" 
```

**Comment by assawalhy** [comment]
https://github.com/me00001/compiler/blob/8ac159dfa21fe6c08e76d80287b9dfd9697f0207/%D8%A7%D8%AE%D8%AA%D8%A8%D8%A7%D8%B1%D8%A7%D8%AA/%D8%A7%D8%AE%D8%AA%D8%A8%D8%B1#L101

**Comment by assawalhy** [comment]
<div dir=rtl>

مشكلة آخرى واجهتني أنا وأحمد الطبراني @AhmedElTabarani, وهي على نظام الويندوز، حيث إن المسار يكون به شرطة مائلة لليسار وليس لليمين كما في لينوكس مثلا، وبالتالي هي بالنسبة للجيسون حرف هروب escape carachter.

**ما يحدث حاليا:**

<div dir=ltr>

```json
{"file":"E:\ألف\compiler\اختبارات\أكواد\مكتبات\الرياضيات.alif","line":"6","msg":"أمر غير معروف ' رياضيات ', كان من المتوقع أن يكون إسم مجال"}
```

<div dir=rtl>

**ما هو متوقع:**

<div dir=ltr>

```json
{"file":"E:\\ألف\\compiler\\اختبارات\\أكواد\\مكتبات\\الرياضيات.alif","line":"6","msg":"أمر غير معروف ' رياضيات ', كان من المتوقع أن يكون إسم مجال"}
```

**Comment by hassandraga** [comment]
<div dir=rtl>
كلا المشكلتان ثم حلهما في ألف 3.0.33

كذالك ثم إضافة 
`--log-json-base64`

**Comment by hassandraga** [comment]
<div dir = rtl>
هل ثم الحل؟

**Comment by assawalhy** [comment]
<div dir=rtl>

> هل ثم الحل؟

حُلت والحمد لله
